/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as AdminDashboardV2RouteImport } from "./routes/admin-dashboard-v2";
import { Route as AdminDashboardV1RouteImport } from "./routes/admin-dashboard-v1";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AdminDashboardIndexRouteImport } from "./routes/admin-dashboard/index";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthLoginV2RouteImport } from "./routes/auth/login-v2";
import { Route as AuthLoginV1RouteImport } from "./routes/auth/login-v1";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";
import { Route as AdminDashboardUsersRouteImport } from "./routes/admin-dashboard/users";
import { Route as DashboardMyBallotIndexRouteImport } from "./routes/dashboard/my-ballot/index";
import { Route as AdminDashboardViewResultsIndexRouteImport } from "./routes/admin-dashboard/view-results/index";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminDashboardV2Route = AdminDashboardV2RouteImport.update({
  id: "/admin-dashboard-v2",
  path: "/admin-dashboard-v2",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminDashboardV1Route = AdminDashboardV1RouteImport.update({
  id: "/admin-dashboard-v1",
  path: "/admin-dashboard-v1",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: "/admin-dashboard/",
  path: "/admin-dashboard/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/auth/register",
  path: "/auth/register",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginV2Route = AuthLoginV2RouteImport.update({
  id: "/auth/login-v2",
  path: "/auth/login-v2",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginV1Route = AuthLoginV1RouteImport.update({
  id: "/auth/login-v1",
  path: "/auth/login-v1",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminDashboardUsersRoute = AdminDashboardUsersRouteImport.update({
  id: "/admin-dashboard/users",
  path: "/admin-dashboard/users",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardMyBallotIndexRoute = DashboardMyBallotIndexRouteImport.update({
  id: "/dashboard/my-ballot/",
  path: "/dashboard/my-ballot/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminDashboardViewResultsIndexRoute = AdminDashboardViewResultsIndexRouteImport.update({
  id: "/admin-dashboard/view-results/",
  path: "/admin-dashboard/view-results/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/admin-dashboard-v1": typeof AdminDashboardV1Route;
  "/admin-dashboard-v2": typeof AdminDashboardV2Route;
  "/settings": typeof SettingsRoute;
  "/admin-dashboard/users": typeof AdminDashboardUsersRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/login-v1": typeof AuthLoginV1Route;
  "/auth/login-v2": typeof AuthLoginV2Route;
  "/auth/register": typeof AuthRegisterRoute;
  "/admin-dashboard": typeof AdminDashboardIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/admin-dashboard/view-results": typeof AdminDashboardViewResultsIndexRoute;
  "/dashboard/my-ballot": typeof DashboardMyBallotIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/admin-dashboard-v1": typeof AdminDashboardV1Route;
  "/admin-dashboard-v2": typeof AdminDashboardV2Route;
  "/settings": typeof SettingsRoute;
  "/admin-dashboard/users": typeof AdminDashboardUsersRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/login-v1": typeof AuthLoginV1Route;
  "/auth/login-v2": typeof AuthLoginV2Route;
  "/auth/register": typeof AuthRegisterRoute;
  "/admin-dashboard": typeof AdminDashboardIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/admin-dashboard/view-results": typeof AdminDashboardViewResultsIndexRoute;
  "/dashboard/my-ballot": typeof DashboardMyBallotIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/admin-dashboard-v1": typeof AdminDashboardV1Route;
  "/admin-dashboard-v2": typeof AdminDashboardV2Route;
  "/settings": typeof SettingsRoute;
  "/admin-dashboard/users": typeof AdminDashboardUsersRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/login-v1": typeof AuthLoginV1Route;
  "/auth/login-v2": typeof AuthLoginV2Route;
  "/auth/register": typeof AuthRegisterRoute;
  "/admin-dashboard/": typeof AdminDashboardIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/admin-dashboard/view-results/": typeof AdminDashboardViewResultsIndexRoute;
  "/dashboard/my-ballot/": typeof DashboardMyBallotIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/admin-dashboard-v1"
    | "/admin-dashboard-v2"
    | "/settings"
    | "/admin-dashboard/users"
    | "/auth/login"
    | "/auth/login-v1"
    | "/auth/login-v2"
    | "/auth/register"
    | "/admin-dashboard"
    | "/dashboard"
    | "/admin-dashboard/view-results"
    | "/dashboard/my-ballot";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/admin-dashboard-v1"
    | "/admin-dashboard-v2"
    | "/settings"
    | "/admin-dashboard/users"
    | "/auth/login"
    | "/auth/login-v1"
    | "/auth/login-v2"
    | "/auth/register"
    | "/admin-dashboard"
    | "/dashboard"
    | "/admin-dashboard/view-results"
    | "/dashboard/my-ballot";
  id:
    | "__root__"
    | "/"
    | "/admin-dashboard-v1"
    | "/admin-dashboard-v2"
    | "/settings"
    | "/admin-dashboard/users"
    | "/auth/login"
    | "/auth/login-v1"
    | "/auth/login-v2"
    | "/auth/register"
    | "/admin-dashboard/"
    | "/dashboard/"
    | "/admin-dashboard/view-results/"
    | "/dashboard/my-ballot/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminDashboardV1Route: typeof AdminDashboardV1Route;
  AdminDashboardV2Route: typeof AdminDashboardV2Route;
  SettingsRoute: typeof SettingsRoute;
  AdminDashboardUsersRoute: typeof AdminDashboardUsersRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthLoginV1Route: typeof AuthLoginV1Route;
  AuthLoginV2Route: typeof AuthLoginV2Route;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  AdminDashboardViewResultsIndexRoute: typeof AdminDashboardViewResultsIndexRoute;
  DashboardMyBallotIndexRoute: typeof DashboardMyBallotIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin-dashboard-v2": {
      id: "/admin-dashboard-v2";
      path: "/admin-dashboard-v2";
      fullPath: "/admin-dashboard-v2";
      preLoaderRoute: typeof AdminDashboardV2RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin-dashboard-v1": {
      id: "/admin-dashboard-v1";
      path: "/admin-dashboard-v1";
      fullPath: "/admin-dashboard-v1";
      preLoaderRoute: typeof AdminDashboardV1RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin-dashboard/": {
      id: "/admin-dashboard/";
      path: "/admin-dashboard";
      fullPath: "/admin-dashboard";
      preLoaderRoute: typeof AdminDashboardIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/register": {
      id: "/auth/register";
      path: "/auth/register";
      fullPath: "/auth/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login-v2": {
      id: "/auth/login-v2";
      path: "/auth/login-v2";
      fullPath: "/auth/login-v2";
      preLoaderRoute: typeof AuthLoginV2RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login-v1": {
      id: "/auth/login-v1";
      path: "/auth/login-v1";
      fullPath: "/auth/login-v1";
      preLoaderRoute: typeof AuthLoginV1RouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin-dashboard/users": {
      id: "/admin-dashboard/users";
      path: "/admin-dashboard/users";
      fullPath: "/admin-dashboard/users";
      preLoaderRoute: typeof AdminDashboardUsersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/my-ballot/": {
      id: "/dashboard/my-ballot/";
      path: "/dashboard/my-ballot";
      fullPath: "/dashboard/my-ballot";
      preLoaderRoute: typeof DashboardMyBallotIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin-dashboard/view-results/": {
      id: "/admin-dashboard/view-results/";
      path: "/admin-dashboard/view-results";
      fullPath: "/admin-dashboard/view-results";
      preLoaderRoute: typeof AdminDashboardViewResultsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardV1Route: AdminDashboardV1Route,
  AdminDashboardV2Route: AdminDashboardV2Route,
  SettingsRoute: SettingsRoute,
  AdminDashboardUsersRoute: AdminDashboardUsersRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthLoginV1Route: AuthLoginV1Route,
  AuthLoginV2Route: AuthLoginV2Route,
  AuthRegisterRoute: AuthRegisterRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminDashboardViewResultsIndexRoute: AdminDashboardViewResultsIndexRoute,
  DashboardMyBallotIndexRoute: DashboardMyBallotIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
