/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminDashboardIndexRouteImport } from './routes/admin-dashboard/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardMyBallotIndexRouteImport } from './routes/dashboard/my-ballot/index'
import { Route as AdminDashboardViewResultsIndexRouteImport } from './routes/admin-dashboard/view-results/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/admin-dashboard/',
  path: '/admin-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMyBallotIndexRoute = DashboardMyBallotIndexRouteImport.update({
  id: '/dashboard/my-ballot/',
  path: '/dashboard/my-ballot/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardViewResultsIndexRoute =
  AdminDashboardViewResultsIndexRouteImport.update({
    id: '/admin-dashboard/view-results/',
    path: '/admin-dashboard/view-results/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin-dashboard/view-results': typeof AdminDashboardViewResultsIndexRoute
  '/dashboard/my-ballot': typeof DashboardMyBallotIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin-dashboard': typeof AdminDashboardIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/admin-dashboard/view-results': typeof AdminDashboardViewResultsIndexRoute
  '/dashboard/my-ballot': typeof DashboardMyBallotIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/admin-dashboard/': typeof AdminDashboardIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/admin-dashboard/view-results/': typeof AdminDashboardViewResultsIndexRoute
  '/dashboard/my-ballot/': typeof DashboardMyBallotIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/admin-dashboard'
    | '/dashboard'
    | '/admin-dashboard/view-results'
    | '/dashboard/my-ballot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/admin-dashboard'
    | '/dashboard'
    | '/admin-dashboard/view-results'
    | '/dashboard/my-ballot'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/admin-dashboard/'
    | '/dashboard/'
    | '/admin-dashboard/view-results/'
    | '/dashboard/my-ballot/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AdminDashboardViewResultsIndexRoute: typeof AdminDashboardViewResultsIndexRoute
  DashboardMyBallotIndexRoute: typeof DashboardMyBallotIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/': {
      id: '/admin-dashboard/'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/my-ballot/': {
      id: '/dashboard/my-ballot/'
      path: '/dashboard/my-ballot'
      fullPath: '/dashboard/my-ballot'
      preLoaderRoute: typeof DashboardMyBallotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard/view-results/': {
      id: '/admin-dashboard/view-results/'
      path: '/admin-dashboard/view-results'
      fullPath: '/admin-dashboard/view-results'
      preLoaderRoute: typeof AdminDashboardViewResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AdminDashboardViewResultsIndexRoute: AdminDashboardViewResultsIndexRoute,
  DashboardMyBallotIndexRoute: DashboardMyBallotIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
